### ISSUE TITLE
Remove header required?

### ISSUE THREAD

**Issue by mark-church** [howardjohn/service-apis-demo#1]
I got the following error when applying this HTTPRoute:

```
kubectl apply -f multi-route-gateway/baz-httproute.yaml
error: error validating "multi-route-gateway/baz-httproute.yaml": error validating data: [ValidationError(HTTPRoute.spec.hosts[0].rules[0].filter.headers): missing required field "remove" in io.x-k8s.networking.v1alpha1.HTTPRoute.spec.hosts.rules.filter.headers, ValidationError(HTTPRoute.spec.hosts[0].rules[1].filter.headers): missing required field "remove" in io.x-k8s.networking.v1alpha1.HTTPRoute.spec.hosts.rules.filter.headers]; if you choose to ignore these errors, turn validation off with --validate=false
```

I'm not sure if this is an Istio issue or a Gateway spec issue. If it's a spec issue then I'll refile there. My expectation is that we can add and remove headers independently. @robscott

```
apiVersion: networking.x-k8s.io/v1alpha1
kind: HTTPRoute
metadata:
  name: baz-route
  namespace: gateway-demo
spec:
  hosts:
  - hostnames: ["baz.com"]
    rules:
    - match:
        path: /store
      filter:
        headers:
          add:
            path: store
      action:
        forwardTo:
        - targetRef:
            name: baz-svc
    - match:
        path: /profile
      filter:
        headers:
          add:
            path: profile
      action:
        forwardTo:
        - targetRef:
            name: baz-svc
```
